
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class BMI extends javax.swing.JFrame {

    /**
     * Creates new form BMI
     */
    public BMI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txt1 = new javax.swing.JTextField();
        Txt2 = new javax.swing.JTextField();
        Txt3 = new javax.swing.JTextField();
        Txt4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculator BMI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Jenis Kelamin");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Umur :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("BMI");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tinggi (m) :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Berat (kg) :");

        Txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Pria");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Wanita");

        Btn1.setText("Hitung");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setText("Clear");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn3.setText("Exit");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 0, 204));

        jLabel8.setBackground(new java.awt.Color(255, 0, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\animebmi.jpg")); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setMaximumSize(new java.awt.Dimension(404, 400));
        jLabel8.setPreferredSize(new java.awt.Dimension(564, 258));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(Txt4)
                    .addComponent(Btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn2)
                    .addComponent(Btn3)
                    .addComponent(Btn1))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        Txt1.setText("");
        Txt2.setText("");
        Txt3.setText("");
         Txt4.setText("");
        Txt2.setOpaque(true);
        Txt2.setBackground(null);
        jLabel7.setText("");
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
 double berat = Double.parseDouble(Txt4.getText()); 
  double tinggi = Double.parseDouble(Txt3.getText());
  double usia = Double.parseDouble(Txt1.getText());
    
   
   double bmi = berat / (tinggi * tinggi);
 
   
   String cal = String.format("%.2f",bmi);
        Txt2.setText(cal);
        
  if (usia >= 11 && usia <= 17) {
    if (usia == 11) {
        if (bmi < 13.9) {
            // Kurang ideal untuk usia 11
               Txt2.setOpaque(true);
              Txt2.setBackground(Color.blue);
            jLabel7.setForeground(Color.blue);
            jLabel7.setText("Tidak Ideal");
            // Lakukan tindakan sesuai kebutuhan
        } else if (bmi >= 13.9 && bmi <= 19.9) {
            // Ideal untuk usia 11
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.green);
            jLabel7.setForeground(Color.green);
            jLabel7.setText("Ideal");
        } else if (bmi > 19.9) {
            // Obesitas untuk usia 11
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.red);
            jLabel7.setForeground(Color.red);
            jLabel7.setText("obesitas");
        }
    } else if (usia >= 12 && usia <= 17) {
        if (usia == 12) {
            if (bmi < 14.4) {
                // Kurang ideal untuk usia 12
                Txt2.setOpaque(true);
                Txt2.setBackground(Color.blue);
                jLabel7.setForeground(Color.blue);
                jLabel7.setText("Tidak Ideal");
            } else if (bmi >= 14.4 && bmi <= 20.8) {
                // Ideal untuk usia 12
               Txt2.setOpaque(true);
                Txt2.setBackground(Color.green);
                jLabel7.setForeground(Color.green);
                jLabel7.setText("Ideal");
            } else if (bmi > 20.8) {
                // Obesitas untuk usia 12
                Txt2.setOpaque(true);
                Txt2.setBackground(Color.red);
                jLabel7.setForeground(Color.red);
                jLabel7.setText("obesitas");
            }
        } else if (usia >= 13 && usia <= 17) {
            if (usia == 13) {
                if (bmi < 14.9) {
                   // Kurang ideal untuk usia 14
                    Txt2.setOpaque(true);
                    Txt2.setBackground(Color.blue);
                    jLabel7.setForeground(Color.blue);
                    jLabel7.setText("Tidak Ideal");
                } else if (bmi >= 14.9 && bmi <= 22.7) {
                    // Ideal untuk usia 13
                    Txt2.setOpaque(true);
                    Txt2.setBackground(Color.green);
                    jLabel7.setForeground(Color.green);
                    jLabel7.setText("Ideal");
                } else if (bmi > 22.7) {
                // Obesitas untuk usia 13
                Txt2.setOpaque(true);
                Txt2.setBackground(Color.red);
                jLabel7.setForeground(Color.red);
                jLabel7.setText("obesitas");
                }
            }else if (usia >= 14 && usia <= 17) {
            if (usia == 14) {
                if (bmi < 15.4) {
                    // Kurang ideal untuk usia 14
                       Txt2.setOpaque(true);
              Txt2.setBackground(Color.blue);
            jLabel7.setForeground(Color.blue);
            jLabel7.setText("Tidak Ideal");
                    // Lakukan tindakan sesuai kebutuhan
                } else if (bmi >= 15.4 && bmi <= 22.7) {
                    // Ideal untuk usia 14
                    Txt2.setOpaque(true);
                    Txt2.setBackground(Color.green);
                    jLabel7.setForeground(Color.green);
                    jLabel7.setText("Ideal");
                } else if (bmi > 22.7) {
                    // Obesitas untuk usia 14
                    Txt2.setOpaque(true);
                    Txt2.setBackground(Color.red);
                    jLabel7.setForeground(Color.red);
                    jLabel7.setText("obesitas");
                }
            }else if (usia >= 15 && usia <= 17) {
            if (usia == 15) {
                if (bmi < 15.9) {
                    // Kurang ideal untuk usia 15
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.blue);
            jLabel7.setForeground(Color.blue);
            jLabel7.setText("Tidak Ideal");
                } else if (bmi >= 15.9 && bmi <= 23.5) {
                    // Ideal untuk usia 15
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.green);
            jLabel7.setForeground(Color.green);
            jLabel7.setText("Ideal");
                } else if (bmi > 23.5) {
                    // Obesitas untuk usia 15
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.red);
            jLabel7.setForeground(Color.red);
            jLabel7.setText("obesitas");
            }
            }else if (usia >= 16 && usia <= 17) {
            if (usia == 16) {
                if (bmi < 16.2) {
                    // Kurang ideal untuk usia 16
                       Txt2.setOpaque(true);
              Txt2.setBackground(Color.blue);
            jLabel7.setForeground(Color.blue);
            jLabel7.setText("Tidak Ideal");
                } else if (bmi >= 16.2 && bmi <= 24.1) {
                    // Ideal untuk usia 16
                      Txt2.setOpaque(true);
            Txt2.setBackground(Color.green);
            jLabel7.setForeground(Color.green);
            jLabel7.setText("Ideal");
                } else if (bmi > 24.1) {
                    // Obesitas untuk usia 16
                       Txt2.setOpaque(true);
            Txt2.setBackground(Color.red);
            jLabel7.setForeground(Color.red);
            jLabel7.setText("obesitas");
                }
            }else if (usia == 17) {
                if (bmi < 16.4) {
                    // Kurang ideal untuk usia 17
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.blue);
            jLabel7.setForeground(Color.blue);
            jLabel7.setText("Tidak Ideal");
                } else if (bmi >= 16.4 && bmi <= 26.5) {
                    // Ideal untuk usia 17
                      Txt2.setOpaque(true);
            Txt2.setBackground(Color.green);
            jLabel7.setForeground(Color.green);
            jLabel7.setText("Ideal");
                } else if (bmi > 26.5) {
                    // Obesitas untuk usia 17
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.red);
            jLabel7.setForeground(Color.red);
            jLabel7.setText("obesitas");
            
                }
            
            
                        }
                    }
                }
            }
        }
    }
} else {
    // Usia diluar rentang 11-17
    if (bmi <= 18.5) {
            Txt2.setOpaque(true);
              Txt2.setBackground(Color.blue);
            jLabel7.setForeground(Color.blue);
            jLabel7.setText("Tidak Ideal");
        } else if (bmi <= 25) {
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.green);
            jLabel7.setForeground(Color.green);
            jLabel7.setText("Ideal");
        } else if (bmi <= 30) {
            Txt2.setOpaque(true);
            Txt2.setBackground(Color.orange);
            jLabel7.setForeground(Color.orange);
            jLabel7.setText("Gemuk");
        }else{
             Txt2.setOpaque(true);
            Txt2.setBackground(Color.red);
            jLabel7.setForeground(Color.red);
            jLabel7.setText("obesitas");
        }
    // Lakukan tindakan sesuai kebutuhan
}
      
            
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JTextField Txt1;
    private javax.swing.JTextField Txt2;
    private javax.swing.JTextField Txt3;
    private javax.swing.JTextField Txt4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
